### ISSUE TITLE
GAN inversion using images with piercings

### ISSUE THREAD

**Issue by AndrMoura** [wty-ustc/e2style#15]
Hello, Im trying to do some images inversions that contain earrings, nose piercings that kind of stuff and I notice that are they are not captured in the inverted image, e.g.:

![learned_img_black_man_earring](https://user-images.githubusercontent.com/8346098/178483361-4d1ad400-7b5a-4fd3-991a-29ef9afd5888.png)
![nose_piercing](https://user-images.githubusercontent.com/8346098/178483788-3e6c2fc2-8393-48b9-a92c-604bce6eba9c.png)

Any tips to make the algorithm more sensitive to local features? Thank you!

**Comment by adeelnazar** [comment]
hi  Andr moura

how to perform inversion with e2style pleases guide me i performed stylemixing it gives me error inversion first then stylemixing ang how to get image_list.txt and latent_code.npy file on corresponding folder

thanks in advance

**Comment by adeelnazar** [comment]
when i run this code below in colab

!python scripts/stylemixing.py \
--save_inverted_codes\
--resize_outputs\
--exp_dir='/content/gdrive/My Drive/result'\
--checkpoint_path='/content/gdrive/My Drive/model/inversion.pt' \
--style_dir='/content/gdrive/My Drive/style/style1.jpg' \
--content_dir='/content/gdrive/My Drive/content/adeel1.jpg'

then i got this error

Loading generator.
Traceback (most recent call last):
  File "scripts/stylemixing.py", line 96, in <module>
    main()
  File "scripts/stylemixing.py", line 39, in main
    assert os.path.exists(f'{style_dir}/image_list.txt')
AssertionError

**Comment by wtybest** [comment]
My method targets the W+ space of StyleGAN, which is limited by the representational power of that space, and these high-frequency information are difficult to be accurately inverted. Therefore, some methods ([Barbershop](https://github.com/ZPdesu/Barbershop), [HFGI](https://github.com/Tengfei-Wang/HFGI)) introduce feature spaces for achieving better reconstruction. You can try that idea.
